apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - porkbun-webhook.yaml
  - nfd.yaml
  - intel-device-plugins-operator.yaml
  - intel-gpu-plugin.yaml
